#!/usr/bin/env python3
from pathlib import Path
import re, csv, sys
ROOT=Path(__file__).resolve().parents[1]
RDIR=ROOT/'R'
issues=[]; checks=[]

def record(name, ok, detail=''):
    checks.append((name,'PASS' if ok else 'FAIL',detail))
    if not ok: issues.append((name,detail))

# Required package files
for rel in ['DESCRIPTION','NAMESPACE','LICENSE','README.md','tests/testthat.R','tools/VALIDATION_LOCAL.md']:
    record(f'file:{rel}',(ROOT/rel).exists())

# Delimiter balance ignoring R comments and quoted strings.
for f in sorted(RDIR.glob('*.R')):
    s=f.read_text(); stack=[]; quote=None; esc=False; comment=False; line=1; err=''
    pairs={')':'(',']':'[','}':'{'}
    for ch in s:
        if ch=='\n': line+=1; comment=False; continue
        if comment: continue
        if quote:
            if esc: esc=False
            elif ch=='\\': esc=True
            elif ch==quote: quote=None
            continue
        if ch=='#': comment=True; continue
        if ch in ('"',"'",'`'): quote=ch; continue
        if ch in '([{': stack.append((ch,line))
        elif ch in pairs:
            if not stack or stack[-1][0]!=pairs[ch]: err=f'unexpected {ch} line {line}';break
            stack.pop()
    if not err and stack: err=f'unclosed {stack[-1][0]} line {stack[-1][1]}'
    record(f'delimiters:{f.name}',not err,err)

# Functions, duplicates, namespace.
funcs={}; dup=[]
for f in sorted(RDIR.glob('*.R')):
    for ln,l in enumerate(f.read_text().splitlines(),1):
        m=re.match(r'\s*([A-Za-z.][A-Za-z0-9._]*)\s*<-\s*function\b',l)
        if m:
            n=m.group(1)
            if n in funcs: dup.append(n)
            funcs[n]=(f.name,ln)
record('function_names_unique',not dup,','.join(sorted(set(dup))))
ns=(ROOT/'NAMESPACE').read_text()
exports=re.findall(r'export\(([^)]+)\)',ns)
record('namespace_exports_exist',all(e in funcs for e in exports),','.join(e for e in exports if e not in funcs))
record('namespace_roxygen_header',ns.startswith('# Generated by roxygen2: do not edit by hand'))

# Teaching data and vignette policy.
csvs=list((ROOT/'inst/extdata').glob('*.csv'))
record('agronomic_teaching_datasets',len(csvs)>=6,f'{len(csvs)} datasets')
vigs=list((ROOT/'vignettes').glob('*.Rmd'))
record('vignette_count',len(vigs)>=21,f'{len(vigs)} vignettes')
record('integrated_tutorial',(ROOT/'vignettes/21-foundations-to-advanced-tutorial.Rmd').exists())

# Every exported function appears at least three times across vignette sources.
text='\n'.join(v.read_text() for v in vigs)
counts={e:len(re.findall(r'\b'+re.escape(e)+r'\s*\(',text)) for e in exports}
record('vignette_api_usage_ge3',all(v>=3 for v in counts.values()),','.join(f'{k}:{v}' for k,v in counts.items() if v<3))
with (ROOT/'inst/metadata/vignette_api_coverage.csv').open('w',newline='') as fh:
    w=csv.writer(fh);w.writerow(['function','vignette_calls','status'])
    for k in sorted(counts):w.writerow([k,counts[k],'PASS' if counts[k]>=3 else 'FAIL'])

# User-controlled bootstrap in primary publication APIs.
pub=(RDIR/'plots.R').read_text()+(RDIR/'tables.R').read_text()+(RDIR/'bootstrap.R').read_text()
record('publication_bootstrap_R_argument','R=999L' in pub or 'R = 999L' in pub)
record('bootstrap_ci_fields',all(x in pub for x in ['conf_low','conf_high']))

# Optional Python/Julia must not be Imports.
desc=(ROOT/'DESCRIPTION').read_text()
imports=desc.split('Suggests:')[0]
record('python_julia_not_mandatory',all(x not in imports for x in ['reticulate','JuliaCall','PythonCall']))

out=ROOT/'inst/metadata/static_validation.csv'
with out.open('w',newline='') as fh:
    w=csv.writer(fh);w.writerow(['check','status','detail']);w.writerows(checks)
for c,s,d in checks: print(f'{s:4s} {c}' + (f' :: {d}' if d else ''))
print(f'\nStatic validation: {sum(s=="PASS" for _,s,_ in checks)}/{len(checks)} PASS')
sys.exit(1 if issues else 0)
